customs_declarations_database/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from .views import upload_gtd, show_gtd_file, CDDLogin, CDDLogout, GtdGoodDeleteView,\
    GtdDetailView, update_gtd, GtdDeleteView, Profile, handbook_xlsx, HandbookUpdateView,\
    eco_fee, to_wms, AccessDeniedView, to_erp, StatisticsMenu, GtdGroupDeleteView, users_list,\
    statistics_report_gtd_per_exporter, statistics_report_goods_imported, report_xlsx, ChangeUserInfoView,\
    RegUserPasswordChangeView, RegisterUserView, RegisterDoneView, user_activate, show_gtd_list, HandbookDeleteView,\
    GtdGroupUpdateView, GtdGoodUpdateView, GtdGoodCreateView, GtdGroupCreateView, HandbookListView, HandbookCreateView,\
    UserUpdateView, UserDeleteView, CDDPasswordResetView, CDDPasswordResetDoneView, CDDPasswordResetCompleteView,\
    CDDPasswordResetConfirmView


app_name = 'main'
urlpatterns = [
    path('handbook_xlsx/<path:filename>', handbook_xlsx, name='handbook_xlsx'),
    # path('handbook/<str:choice>', handbook, name='handbook'),
    path('handbook/<str:handbook>/delete/<int:pk>', HandbookDeleteView.as_view(), name='delete_handbook_entry'),
    path('handbook/<str:handbook>/create', HandbookCreateView.as_view(), name='create_handbook_entry'),
    path('handbook/<str:handbook>/update/<int:pk>', HandbookUpdateView.as_view(), name='update_handbook'),
    path('handbook/<str:handbook>/', HandbookListView.as_view(), name='handbook'),
    path('accounts/password/reset/done', CDDPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password/reset/confirm/<uidb64>/<token>/', CDDPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/password/reset/complete', CDDPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/password/reset/', CDDPasswordResetView.as_view(), name='password_reset'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/password/change', RegUserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/change', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/', Profile.as_view(), name='profile'),
    path('accounts/login/', CDDLogin.as_view(), name='login'),
    path('accounts/logout/', CDDLogout.as_view(), name='logout'),
    path('statistics/goods_imported', statistics_report_goods_imported, name='report_goods_imported'),
    path('statistics/gtd_per_exporter', statistics_report_gtd_per_exporter, name='statistics_gtd_per_exporter'),
    path('statistics/menu', StatisticsMenu.as_view(), name='statistics_menu'),
    path('eco_fee', eco_fee, name='eco_fee'),
    path('report_xlsx/<path:folder>/<path:filename>', report_xlsx, name='report_xlsx'),
    path('documents/delete_gtd_good/<int:pk>', GtdGoodDeleteView.as_view(), name='delete_gtd_good'),
    path('documents/delete_gtd_group/<int:pk>', GtdGroupDeleteView.as_view(), name='delete_gtd_group'),
    path('documents/update_gtd_group/<int:pk>', GtdGroupUpdateView.as_view(), name='update_gtd_group'),
    path('documents/update_gtd_good/<int:pk>', GtdGoodUpdateView.as_view(), name='update_gtd_good'),
    path('documents/create_good/<int:pk>', GtdGoodCreateView.as_view(), name='create_gtd_good'),
    path('documents/create_gtd_group/<int:pk>', GtdGroupCreateView.as_view(), name='create_gtd_group'),
    path('documents/update_gtd/<int:pk>', update_gtd, name='update_gtd'),
    path('documents/delete_gtd/<int:pk>', GtdDeleteView.as_view(), name='delete_gtd'),
    path('documents/show_gtd/file/<path:filename>', show_gtd_file, name='show_gtd_file'),
    path('erp/<int:pk>', to_erp, name='to_erp'),
    path('wms/<int:pk>', to_wms, name='to_wms'),
    path('documents/show_gtd/<int:pk>', GtdDetailView.as_view(), name='per_gtd'),
    path('documents/upload_gtd', upload_gtd, name='upload_gtd'),
    path('access_denied', AccessDeniedView.as_view(), name='access_denied'),
    path('users/delete/<int:pk>', UserDeleteView.as_view(), name='user_delete'),
    path('users/update/<int:pk>', UserUpdateView.as_view(), name='user_update'),
    path('users', users_list, name='users'),
    path('', show_gtd_list, name='show_gtd'),
]

main/views.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView,\
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.signing import BadSignature
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from .forms import UploadGtdfilesForm, GtdUpdateForm, GtdGoodCreateUpdateForm, \
    CalendarDate, ExportComment, ChangeUserInfoForm, RegisterUserForm, GtdGroupCreateUpdateForm, \
    CustomsHouseHandbookCreateUpdateForm, ExporterHandbookCreateUpdateForm, ImporterHandbookCreateUpdateForm, \
    CountryHandbookCreateUpdateForm, \
    CurrencyHandbookCreateUpdateForm, DealTypeHandbookCreateUpdateForm, TnVedHandbookCreateUpdateForm, \
    ProcedureHandbookCreateUpdateForm, \
    GoodHandbookCreateUpdateForm, TradeMarkHandbookCreateUpdateForm, GoodsMarkHandbookCreateUpdateForm, \
    ManufacturerHandbookCreateUpdateForm, \
    MeasureQualifierHandbookCreateUpdateForm, DocumentTypeHandbookCreateUpdateForm, SearchForm, HandbookSearchForm
from .models import GtdMain, GtdGroup, GtdGood, UploadGtd, CustomsHouse, Exporter, Country, Currency, Importer, DealType,\
    Procedure, TnVed, Good, GoodsMark, GtdDocument, Document, TradeMark, Manufacturer, MeasureQualifier, DocumentType,\
    UploadGtdFile, Handbook
import os
from .utilities import parse_gtd, get_tnved_name, signer
from .models import RegUser
from customs_declarations_database.settings import MEDIA_ROOT
from customs_declarations_database.Constant import under
import xlsxwriter
import mimetypes
import pandas as pd
from datetime import datetime


def paginate_func(raw_data, request, auto):
    """
    Вспомогательная функция для некоторых представлений-функций,
    принимающая массив данных и запрос на вход и возвращающая пагинированные данные
    """
    paginate_by = request.GET.get('paginate_by', auto)
    page = request.GET.get('page', 1)
    paginator = Paginator(raw_data, paginate_by)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    return data, paginate_by


def roles_required(allowed_roles=[]):
    """
    Декоратор, проверяющий наличие у пользователя нужной роли
    """
    def decorator(view_func):
        def wrap(request, *args, **kwargs):
            if request.user.role and request.user.role.name in allowed_roles:
                return view_func(request, *args, **kwargs)
            else:
                return HttpResponseRedirect(reverse_lazy('main:access_denied'))
        return wrap
    return decorator


class AccessDeniedView(TemplateView):
    """
    Представление страницы уведомления об ограничении доступа
    """
    template_name = 'main/no_access.html'


class CDDLogin(LoginView):
    """
    Представление для авторизации
    """
    template_name = 'main/login.html'


class CDDLogout(LogoutView, LoginRequiredMixin):
    """
    Представление для выхода из аккаунта
    """
    template_name = 'main/logout.html'


class ChangeUserInfoView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Представление для изменения данных пользователя
    """
    model = RegUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        """
        Метод определяет атрибут, нужный в дальнейшем для поиска объекта,
        который будет редактироваться
        """
        self.user_id = request.user.pk
        return super(ChangeUserInfoView, self).setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """
        Получения объекта для редактирования
        """
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class RegUserPasswordChangeView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    """
    Представление для смены пароля
    """
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль успешно изменен'


@method_decorator(roles_required(allowed_roles=['Администратор']), name='dispatch')
class RegisterUserView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Представление для добавления нового пользователя
    """
    model = RegUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')
    success_message = 'Пользователь добавлен'


class RegisterDoneView(TemplateView):
    """
    Представление для вывода сообщения о том, что учетная запись пользователя создана
    (Ещё потребуется активация)
    """
    template_name = 'main/register_done.html'


def user_activate(request, sign):
    """
    Представление для активации аккаунта пользователя после перехода по ссылке
    """
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(RegUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class CDDPasswordResetView(PasswordResetView):
    """Представление для сброса пароля"""
    template_name = 'main/password_reset_form.html'
    email_template_name = 'main/password_reset_email.html'
    success_url = reverse_lazy('main:password_reset_done')


class CDDPasswordResetDoneView(PasswordResetDoneView):
    """
    Представление для уведомления о письме с ссылкой для сброса пароля
    """
    template_name = 'main/password_reset_done.html'


class CDDPasswordResetConfirmView(PasswordResetConfirmView):
    """
    Представление для установления нового пароля
    """
    template_name = 'main/password_reset_confirm.html'
    success_url = reverse_lazy('main:password_reset_complete')


class CDDPasswordResetCompleteView(PasswordResetCompleteView):
    """
    Представление завершения операции сброса пароля
    """
    template_name = 'main/password_reset_complete.html'


@login_required
@roles_required(allowed_roles=['Администратор'])
def users_list(request):
    """
    Представления для вывода списка всех пользователей, возможна фильтрация
    """
    # Получение ключевого слова
    kw = request.GET.get('key', '')

    # Фильтрация по ключевому слову
    q = Q(first_name__icontains=kw) | Q(username__icontains=kw) | Q(last_name__icontains=kw) | \
        Q(patronymic__icontains=kw) | Q(email__icontains=kw) | Q(role__name__icontains=kw)
    users = RegUser.objects.filter(q)

    users, paginate_by = paginate_func(users, request, 10)
    context = {
        'users': users,
        'paginate_by': paginate_by,
        'form': SearchForm(initial={'key': kw, 'paginate_by': paginate_by}),
    }
    return render(request, 'main/users_list.html', context)


@method_decorator(roles_required(allowed_roles=['Администратор']), name='dispatch')
class UserUpdateView(LoginRequiredMixin, UpdateView):
    """
    Представление для изменения данных пользователей
    """
    model = RegUser
    success_url = reverse_lazy('main:users')
    form_class = ChangeUserInfoForm
    template_name = 'main/update_user.html'


@method_decorator(roles_required(allowed_roles=['Администратор']), name='dispatch')
class UserDeleteView(LoginRequiredMixin, DeleteView):
    """
    Представление для удаления пользователя
    """
    model = RegUser
    success_url = reverse_lazy('main:users')
    template_name = 'main/delete_user.html'


class Profile(LoginRequiredMixin, TemplateView):
    """
    Представление для вывода информации профиля пользователя
    """
    template_name = 'main/profile.html'

    def get_context_data(self, **kwargs):
        """
        Получение контекста (переменных) html шаблона
        """
        context = super(Profile, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


@login_required
def show_gtd_list(request):
    """
    Представление для вывода списка ГТД
    (по умолчанию - всего, но возможна фильтрация)
    """
    # Получение ключевого слова
    kw = request.GET.get('key', '')

    # Получение и обработка диапазона дат
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    qstart, qend = Q(), Q()
    if start_date:
        st = datetime.strptime(start_date, '%d-%m-%Y')
        qstart = Q(date__gte=st)
    if end_date:
        en = datetime.strptime(end_date, '%d-%m-%Y')
        qend = Q(date__lte=en)

    # Фильтрация по ключевому слову и времени
    qdate = qstart & qend
    q = Q(gtdId__icontains=kw) | Q(customs_house__house_name__icontains=kw) | \
        Q(order_num__icontains=kw) | Q(total_goods_number__icontains=kw) | \
        Q(exporter__name__icontains=kw) | Q(importer__name__icontains=kw) | Q(trading_country__russian_name__icontains=kw) | \

main/templates/layout/base.html
{% load bootstrap5 %}
{% load static %}
{% load filtertags %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <title>{% block title %}{% endblock %} - База таможенных деклараций</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block extra_links %}{% endblock %}
</head>
<body class="container-fluid ">
    <header class="mb-4">
        <h3 class="display-5 text-center">База таможенных деклараций</h3>
    </header>
    <div class="row">
        <div class="dropdown">
                    {% if user.is_authenticated %}
                        <button class="btn btn-outline-primary dropdown-toggle" type="button"
                            id="documents-dropdown" data-bs-toggle="dropdown" aria-expanded="true">
                            Документы
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="documents-dropdown" >
                            {% if user|has_role:"Администратор" or user|has_role:"Сотрудник таможенного отдела" %}
                            <li><a href="{% url 'main:upload_gtd' %}" class="dropdown-item">Добавить ГТД</a> </li>
                            {% endif %}
                            <li><a href="{% url 'main:show_gtd' %}" class="dropdown-item">ГТД</a></li>
                        </ul>
                    {% if user|has_role:"Бухгалтер" or user|has_role:"Аналитик" or user|has_role:"Администратор" %}
                    <button class="btn btn-outline-primary dropdown-toggle" type="button" id="reports-dropdown"
                    data-bs-toggle="dropdown">Отчёты</button>
                    <ul class="dropdown-menu" aria-labelledby="reports-dropdown">
                        {% if user|has_role:"Аналитик" or user|has_role:"Администратор" %}
                            <li><a href="{% url 'main:statistics_menu' %}" class="dropdown-item">Статистические отчеты</a></li>
                        {% endif %}
                        {% if user|has_role:"Бухгалтер" or user|has_role:"Администратор" %}
                            <li><a href="{% url 'main:eco_fee' %}" class="dropdown-item">Экологический сбор</a> </li>
                        {% endif %}
                    </ul>
                    {% endif %}

                    <button class="btn btn-outline-primary dropdown-toggle" type="button"
                            id="handbooks-dropdown" data-bs-toggle="dropdown">
                        Справочники
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="handbooks-dropdown">
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='currencies' %}">Валюты</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='countries' %}">Государства</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='qualifiers' %}">Единицы измерения</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='importers'%}">Импортеры</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='tn_ved' %}">Классификатор ТН ВЭД</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='doc_types' %}">Классификатор типов документов</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='deal_types' %}">Классификатор характера сделки</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='customs_houses' %}">Отделы таможни</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='manufacturers' %}">Производители (заводы)</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='procedures' %}">Таможенные процедуры</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='trade_marks' %}">Товарные знаки</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='goods' %}">Товары</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='goods_marks' %}">Торговые марки</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:handbook' handbook='exporters' %}">Экспортёры</a> </li>
                    </ul>

                    <button class="btn btn-outline-primary dropdown-toggle" type="button"
                            id="profile-dropdown" data-bs-toggle="dropdown">
                        Профиль
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="profile-dropdown">
                        <li><a class="dropdown-item" href="{% url 'main:profile' %}">Мои данные</a> </li>
                        {% if user|has_role:"Администратор" %}
                            <li><a class="dropdown-item" href="{% url 'main:register' %}">Добавить пользователя</a></li>
                            <li><a class="dropdown-item" href="{% url 'main:users' %}">Пользователи</a> </li>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <li><a class="dropdown-item" href={% url 'main:logout' %}>Выйти</a></li>
                        <div class="dropdown-divider"></div>
                    </ul>
                {% else %}
                    <a class="btn btn-outline-primary" id="login" href={% url 'main:login' %}>Вход</a>
                {% endif %}
        </div>
    </div>

    <div class="row">
        <section class="col border py-2">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </section>
    </div>
    <footer class="mt-3">
        <p class="text-right font-italic"></p>
    </footer>
</body>
</html>