customs_declarations_database/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from .views import upload_gtd, show_gtd_file, CDDLogin, CDDLogout, GtdGoodDeleteView,\
    GtdDetailView, update_gtd, GtdDeleteView, Profile, handbook_xlsx, HandbookUpdateView,\
    eco_fee, to_wms, AccessDeniedView, to_erp, StatisticsMenu, GtdGroupDeleteView, users_list,\
    statistics_report_gtd_per_exporter, statistics_report_goods_imported, report_xlsx, ChangeUserInfoView,\
    RegUserPasswordChangeView, RegisterUserView, RegisterDoneView, user_activate, show_gtd_list, HandbookDeleteView,\
    GtdGroupUpdateView, GtdGoodUpdateView, GtdGoodCreateView, GtdGroupCreateView, HandbookListView, HandbookCreateView,\
    UserUpdateView, UserDeleteView, CDDPasswordResetView, CDDPasswordResetDoneView, CDDPasswordResetCompleteView,\
    CDDPasswordResetConfirmView


app_name = 'main'
urlpatterns = [
    path('handbook_xlsx/<path:filename>', handbook_xlsx, name='handbook_xlsx'),
    # path('handbook/<str:choice>', handbook, name='handbook'),
    path('handbook/<str:handbook>/delete/<int:pk>', HandbookDeleteView.as_view(), name='delete_handbook_entry'),
    path('handbook/<str:handbook>/create', HandbookCreateView.as_view(), name='create_handbook_entry'),
    path('handbook/<str:handbook>/update/<int:pk>', HandbookUpdateView.as_view(), name='update_handbook'),
    path('handbook/<str:handbook>/', HandbookListView.as_view(), name='handbook'),
    path('accounts/password/reset/done', CDDPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password/reset/confirm/<uidb64>/<token>/', CDDPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/password/reset/complete', CDDPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/password/reset/', CDDPasswordResetView.as_view(), name='password_reset'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/password/change', RegUserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/profile/change', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/', Profile.as_view(), name='profile'),
    path('accounts/login/', CDDLogin.as_view(), name='login'),
    path('accounts/logout/', CDDLogout.as_view(), name='logout'),
    path('statistics/goods_imported', statistics_report_goods_imported, name='report_goods_imported'),
    path('statistics/gtd_per_exporter', statistics_report_gtd_per_exporter, name='statistics_gtd_per_exporter'),
    path('statistics/menu', StatisticsMenu.as_view(), name='statistics_menu'),
    path('eco_fee', eco_fee, name='eco_fee'),
    path('report_xlsx/<path:folder>/<path:filename>', report_xlsx, name='report_xlsx'),
    path('documents/delete_gtd_good/<int:pk>', GtdGoodDeleteView.as_view(), name='delete_gtd_good'),
    path('documents/delete_gtd_group/<int:pk>', GtdGroupDeleteView.as_view(), name='delete_gtd_group'),
    path('documents/update_gtd_group/<int:pk>', GtdGroupUpdateView.as_view(), name='update_gtd_group'),
    path('documents/update_gtd_good/<int:pk>', GtdGoodUpdateView.as_view(), name='update_gtd_good'),
    path('documents/create_good/<int:pk>', GtdGoodCreateView.as_view(), name='create_gtd_good'),
    path('documents/create_gtd_group/<int:pk>', GtdGroupCreateView.as_view(), name='create_gtd_group'),
    path('documents/update_gtd/<int:pk>', update_gtd, name='update_gtd'),
    path('documents/delete_gtd/<int:pk>', GtdDeleteView.as_view(), name='delete_gtd'),
    path('documents/show_gtd/file/<path:filename>', show_gtd_file, name='show_gtd_file'),
    path('erp/<int:pk>', to_erp, name='to_erp'),
    path('wms/<int:pk>', to_wms, name='to_wms'),
    path('documents/show_gtd/<int:pk>', GtdDetailView.as_view(), name='per_gtd'),
    path('documents/upload_gtd', upload_gtd, name='upload_gtd'),
    path('access_denied', AccessDeniedView.as_view(), name='access_denied'),
    path('users/delete/<int:pk>', UserDeleteView.as_view(), name='user_delete'),
    path('users/update/<int:pk>', UserUpdateView.as_view(), name='user_update'),
    path('users', users_list, name='users'),
    path('', show_gtd_list, name='show_gtd'),
]

main/views.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView,\
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.signing import BadSignature
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from .forms import UploadGtdfilesForm, GtdUpdateForm, GtdGoodCreateUpdateForm, \
    CalendarDate, ExportComment, ChangeUserInfoForm, RegisterUserForm, GtdGroupCreateUpdateForm, \
    CustomsHouseHandbookCreateUpdateForm, ExporterHandbookCreateUpdateForm, ImporterHandbookCreateUpdateForm, \
    CountryHandbookCreateUpdateForm, \
    CurrencyHandbookCreateUpdateForm, DealTypeHandbookCreateUpdateForm, TnVedHandbookCreateUpdateForm, \
    ProcedureHandbookCreateUpdateForm, \
    GoodHandbookCreateUpdateForm, TradeMarkHandbookCreateUpdateForm, GoodsMarkHandbookCreateUpdateForm, \
    ManufacturerHandbookCreateUpdateForm, \
    MeasureQualifierHandbookCreateUpdateForm, DocumentTypeHandbookCreateUpdateForm, SearchForm, HandbookSearchForm
from .models import GtdMain, GtdGroup, GtdGood, UploadGtd, CustomsHouse, Exporter, Country, Currency, Importer, DealType,\
    Procedure, TnVed, Good, GoodsMark, GtdDocument, Document, TradeMark, Manufacturer, MeasureQualifier, DocumentType,\
    UploadGtdFile, Handbook
import os
from .utilities import parse_gtd, get_tnved_name, signer
from .models import RegUser
from customs_declarations_database.settings import MEDIA_ROOT
from customs_declarations_database.Constant import under
import xlsxwriter
import mimetypes
import pandas as pd
from datetime import datetime


def paginate_func(raw_data, request, auto):
    """
    Вспомогательная функция для некоторых представлений-функций,
    принимающая массив данных и запрос на вход и возвращающая пагинированные данные
    """
    paginate_by = request.GET.get('paginate_by', auto)
    page = request.GET.get('page', 1)
    paginator = Paginator(raw_data, paginate_by)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    return data, paginate_by


def roles_required(allowed_roles=[]):
    """
    Декоратор, проверяющий наличие у пользователя нужной роли
    """
    def decorator(view_func):
        def wrap(request, *args, **kwargs):
            if request.user.role and request.user.role.name in allowed_roles:
                return view_func(request, *args, **kwargs)
            else:
                return HttpResponseRedirect(reverse_lazy('main:access_denied'))
        return wrap
    return decorator


class AccessDeniedView(TemplateView):
    """
    Представление страницы уведомления об ограничении доступа
    """
    template_name = 'main/no_access.html'


class CDDLogin(LoginView):
    """
    Представление для авторизации
    """
    template_name = 'main/login.html'


class CDDLogout(LogoutView, LoginRequiredMixin):
    """
    Представление для выхода из аккаунта
    """
    template_name = 'main/logout.html'


class ChangeUserInfoView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Представление для изменения данных пользователя
    """
    model = RegUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        """
        Метод определяет атрибут, нужный в дальнейшем для поиска объекта,
        который будет редактироваться
        """
        self.user_id = request.user.pk
        return super(ChangeUserInfoView, self).setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """
        Получения объекта для редактирования
        """
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class RegUserPasswordChangeView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    """
    Представление для смены пароля
    """
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль успешно изменен'


@method_decorator(roles_required(allowed_roles=['Администратор']), name='dispatch')
class RegisterUserView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Представление для добавления нового пользователя
    """
    model = RegUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')
    success_message = 'Пользователь добавлен'


class RegisterDoneView(TemplateView):
    """
    Представление для вывода сообщения о том, что учетная запись пользователя создана
    (Ещё потребуется активация)
    """
    template_name = 'main/register_done.html'


def user_activate(request, sign):
    """
    Представление для активации аккаунта пользователя после перехода по ссылке
    """
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(RegUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class CDDPasswordResetView(PasswordResetView):
    """Представление для сброса пароля"""
    template_name = 'main/password_reset_form.html'
    email_template_name = 'main/password_reset_email.html'
    success_url = reverse_lazy('main:password_reset_done')


class CDDPasswordResetDoneView(PasswordResetDoneView):
    """
    Представление для уведомления о письме с ссылкой для сброса пароля
    """
    template_name = 'main/password_reset_done.html'


class CDDPasswordResetConfirmView(PasswordResetConfirmView):
    """
    Представление для установления нового пароля
    """
    template_name = 'main/password_reset_confirm.html'
    success_url = reverse_lazy('main:password_reset_complete')


class CDDPasswordResetCompleteView(PasswordResetCompleteView):
    """
    Представление завершения операции сброса пароля
    """
    template_name = 'main/password_reset_complete.html'


@login_required
@roles_required(allowed_roles=['Администратор'])
def users_list(request):
    """
    Представления для вывода списка всех пользователей, возможна фильтрация
    """
    # Получение ключевого слова
    kw = request.GET.get('key', '')

    # Фильтрация по ключевому слову
    q = Q(first_name__icontains=kw) | Q(username__icontains=kw) | Q(last_name__icontains=kw) | \
        Q(patronymic__icontains=kw) | Q(email__icontains=kw) | Q(role__name__icontains=kw)
    users = RegUser.objects.filter(q)

    users, paginate_by = paginate_func(users, request, 10)
    context = {
        'users': users,
        'paginate_by': paginate_by,
        'form': SearchForm(initial={'key': kw, 'paginate_by': paginate_by}),
    }
    return render(request, 'main/users_list.html', context)


@method_decorator(roles_required(allowed_roles=['Администратор']), name='dispatch')
class UserUpdateView(LoginRequiredMixin, UpdateView):
    """
    Представление для изменения данных пользователей
    """
    model = RegUser
    success_url = reverse_lazy('main:users')
    form_class = ChangeUserInfoForm
    template_name = 'main/update_user.html'


@method_decorator(roles_required(allowed_roles=['Администратор']), name='dispatch')
class UserDeleteView(LoginRequiredMixin, DeleteView):
    """
    Представление для удаления пользователя
    """
    model = RegUser
    success_url = reverse_lazy('main:users')
    template_name = 'main/delete_user.html'


class Profile(LoginRequiredMixin, TemplateView):
    """
    Представление для вывода информации профиля пользователя
    """
    template_name = 'main/profile.html'

    def get_context_data(self, **kwargs):
        """
        Получение контекста (переменных) html шаблона
        """
        context = super(Profile, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


@login_required
def show_gtd_list(request):
    """
    Представление для вывода списка ГТД
    (по умолчанию - всего, но возможна фильтрация)
    """
    # Получение ключевого слова
    kw = request.GET.get('key', '')

    # Получение и обработка диапазона дат
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    qstart, qend = Q(), Q()
    if start_date:
        st = datetime.strptime(start_date, '%d-%m-%Y')
        qstart = Q(date__gte=st)
    if end_date:
        en = datetime.strptime(end_date, '%d-%m-%Y')
        qend = Q(date__lte=en)

    # Фильтрация по ключевому слову и времени
    qdate = qstart & qend
    q = Q(gtdId__icontains=kw) | Q(customs_house__house_name__icontains=kw) | \
        Q(order_num__icontains=kw) | Q(total_goods_number__icontains=kw) | \
        Q(exporter__name__icontains=kw) | Q(importer__name__icontains=kw) | Q(trading_country__russian_name__icontains=kw) | \

main/templates/main/bad_signature.html
{% extends 'layout/base.html' %}

{% block title %}Ошибка при активации{% endblock %}

{% block content %}
    <h2>Активация прошла неудачно, приносим свои извинения</h2>
{% endblock %}

main/templates/main/create_update_handbook_entry.html
{% extends 'layout/base.html' %}

{% load bootstrap5 %}
{% load static %}

{% block title %} Редактирование записи справочника {% endblock %}

{% block content %}
    <h3>Справочник - <a type="button" data-bs-toggle="modal" data-bs-target="#to_list" href="#"> {{ handbook_name }} </a>- Редактировать запись</h3>
    <div class="modal fade" id="to_list" tabindex="-1" role="dialog" aria-labelledby="to_listLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="to_listLabel">Хотите отменить изменения?</h5>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-label="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Изменения не будут сохранены. Нажмите ОК, если хотите вернуться на страницу списка
                    </div>
                    <div class="modal-footer justify-content-center">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Назад</button>
                        <a class="btn btn-primary" href="{% url 'main:handbook' handbook=handbook %}">ОК </a>
                    </div>
                </div>
            </div>
        </div>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='ОК' %}{% endbuttons %}
        <button class="btn btn-secondary" type="button" data-bs-toggle="modal" data-bs-target="#to_list">Назад</button>
    </form>
{% endblock %}

main/templates/main/delete_gtd.html
{% extends 'layout/base.html' %}

{% load bootstrap5 %}
{% load static %}

{% block title %}
    Удалить ГТД {{ gtd.gtdId }}
{% endblock %}

{% block content %}
    <h3>Удаление ГТД {{ gtd.gtdId }}</h3>
    <form method="post">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить ГТД с этим номером?</p>
        {{ form }}
        <input class="btn btn-danger" type="submit" value="Подтвердить">
    </form>
{% endblock %}

main/templates/main/delete_user.html
{% extends 'layout/base.html' %}

{% load bootstrap5 %}

{% block title %}Удалить пользователя {% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
        <p>Вы уверены, что хотите удалить пользователя?</p>
        {% bootstrap_form form %}
        {% buttons submit='ОК' %}{% endbuttons %}
        <a class="btn btn-secondary" href="{% url 'main:users' %}">Назад</a>
    </form>
{% endblock %}

main/templates/main/profile.html
{% extends 'layout/base.html' %}
{% load bootstrap5 %}

{% load filtertags %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<h2>Сотрудник {{ user.username }}</h2>
<p>Здравствуйте!</p>

    <div class="container-fluid">
        <div>
            {% if user.first_name %}
                Имя: {{ user.first_name }}
            {% else %}
                Имя пользователя не введено
            {% endif %}
        </div>
        <div>
            {% if user.last_name %}
                Фамилия: {{ user.last_name }}
            {% else %}
                Фамилия пользователя не задана
            {% endif %}
        </div>
        <div>
            {% if user.patronymic %}
                Отчество: {{ user.patronymic }}
            {% else %}
                Отчество не задано
            {% endif %}
        </div>
        <div>
            Электронный адрес: {{ user.email }}
        </div>
        <div>
            {% if user.role %}
                Должность: {{ user.role }}
            {% else %}
                Должность не задана
            {% endif %}
        </div>
        <a class="btn btn-outline-info" href="{% url 'main:profile_change' %}">
            Изменить данные профиля
        </a>
        <a class="btn btn-outline-info" href="{% url 'main:password_change' %}">
            Изменить пароль
        </a>
    </div>

{% endblock %}

main/templates/main/show_gtd.html
{% extends "layout/base.html" %}
{% load bootstrap5 %}
{% load static %}
{% block title %}ГТД{% endblock %}

{% block extra_links %}
    <link rel="stylesheet" href="{% static 'main/css/gtd_tables.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/flatpickr.min.css' %}" type="text/css">
    <script src="{% static 'main/js/table_sort.js' %}"></script>
{% endblock %}

{% block content %}
    <h2>Таможенные декларации</h2>
    <h5>Щелкните по цифре в колонке "Число групп товаров", чтобы перейти к группам ГТД</h5>


    <form class="col-md-auto form-inline" method="get">
        <div class="row">
            <div class="col-lg-7">
                {% bootstrap_form search_form layout='horizontal' %}
            </div>
            <div class="col-sm-7">
                <p>Фильтрация по дате: </p>
                {% bootstrap_form calendar_form layout='horizontal' %}
            </div>
        </div>
    {% buttons submit='Искать' %}{% endbuttons %}
    </form>



    <div style="text-align: center">
    <div style="font-size: 150%">
        {% if start or end %}
            {% if start %}{{ start }}{% else %}...{% endif %} - {% if end %}{{ end }} {% else %}...{% endif %}
        {% endif %}
    </div>
    <table size="90%" id="sortable_searchable">
        <thead>
            <tr>
                <th>Номер ГТД</th>
                <th>Таможенный отдел</th>
                <th>Дата</th>
                <th>Экспортер</th>
                <th>Импортер</th>
                <th>Торгующая страна</th>
                <th>Общая стоимость</th>
                <th>Валюта</th>
                <th>Общая стоимость по счёту</th>
                <th>Курс валюты</th>
                <th>xml-файл ГТД</th>
                {% if for_customs_officer %}
                <th>Удалить</th>
                {% endif %}
            </tr>
        </thead>

    <tbody>
        {% for gtd in gtds %}
            <tr>
                <td><a href="{% url 'main:per_gtd' pk=gtd.pk %}">{{ gtd }}</a></td>
                <td>{{ gtd.customs_house.house_name }}</td>
                <td>{{ gtd.date|date:"d.m.Y" }}</td>
                <td>{{ gtd.exporter.name }}</td>
                <td>{{ gtd.importer.name }}</td>
                <td>{{ gtd.trading_country.russian_name }}</td>
                <td>{{ gtd.total_cost }}</td>
                <td>{{ gtd.currency.short_name }}</td>
                <td>{{ gtd.total_invoice_amount }}</td>
                <td>{{ gtd.currency_rate }}</td>
                {% if gtd.gtd_file %}
                    {% url 'main:show_gtd_file' filename=gtd.gtd_file.document as file_url %}
                    <td><a href="{{ file_url }}" target="_blank" >Посмотреть</a> / <a download href={{ file_url }}>Скачать</a> </td>
                {% else %}
                <td>-</td>
                {% endif %}
                {% if for_customs_officer %}
                    <td>
                        <a class="btn btn-outline-danger" href="{% url 'main:delete_gtd' pk=gtd.pk %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg>
                        </a>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
    </table>
    </div>

    {% if gtds.has_other_pages %}
        <nav>
            <ul class="pagination justify-content-center">
                {% if gtds.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?paginate_by={{ paginate_by }}&page={{ gtds.previous_page_number }}&start_date={{ start }}&end_date={{ end }}" aria-label="Назад"> {#  #}
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                    <span class="page-link" aria-hidden="true">&laquo;</span>
                    </li>
                {% endif %}

                {% for p in gtds.paginator.page_range %}
                    {% if gtds.number == p %}
                        <li class="page-item"><a class="page-link" style="color: red;" disabled="true" href="#">{{ p }}</a> </li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?paginate_by={{ paginate_by }}&page={{ p }}&start_date={{ start }}&end_date={{ end }}">{{ p }}</a> </li>  {#  #}
                    {% endif %}
                {% endfor %}

                {% if gtds.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?paginate_by={{ paginate_by }}&page={{ gtds.next_page_number }}&start_date={{ start }}&end_date={{ end }}" aria-label="Далее"> {#  #}
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link" aria-hidden="true">&raquo;</span>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
        <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
        <script>
            config = {
                dateFormat: "d-m-Y",
                altInput: true,
            }
            flatpickr("input[type=date]", config);
        </script>
{% endblock %}

main/templates/main/update_gtd_good.html
{% extends 'layout/base.html' %}

{% load bootstrap5 %}

{% block title %}Редактировать товар{% endblock %}
{% block content %}
    <h3 class="mb-3">
        <a href="#" type="button" data-bs-toggle="modal" data-bs-target="#to_list" >К списку ГТД</a> ->
        К ГТД <a href="#" type="button" data-bs-toggle="modal" data-bs-target="#to_gtd" >{{ good.gtd.gtdId }}</a> ->
        Редактировать товар {{ good.good.marking }}

        <div class="modal fade" id="to_list" tabindex="-1" role="dialog" aria-labelledby="to_listLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="to_listLabel">Хотите отменить изменения?</h5>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-label="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Изменения не будут сохранены. Нажмите ОК, если хотите вернуться на страницу списка
                    </div>
                    <div class="modal-footer justify-content-center">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Назад</button>
                        <a class="btn btn-primary" href="{% url 'main:show_gtd' %}">ОК </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="to_gtd" tabindex="-1" role="dialog" aria-labelledby="to_gtdLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="to_gtdLabel">Хотите отменить изменения?</h5>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-label="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Изменения не будут сохранены. Нажмите ОК, если хотите вернуться на страницу ГТД
                    </div>
                    <div class="modal-footer justify-content-center">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Назад</button>
                        <a class="btn btn-primary" href="{% url 'main:per_gtd' pk=good.gtd.pk %}?group={{ good.group.pk }}">ОК </a>
                    </div>
                </div>
            </div>
        </div>
    </h3>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit='Ок' %}{% endbuttons %}
    </form>
{% endblock %}